// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseBrowser():Promise<void>;

export function CreateProfile(arg1:string,arg2:number):Promise<main.Profile>;

export function DeleteProfile(arg1:string):Promise<void>;

export function GetApps(arg1:string):Promise<Array<main.AppConfig>>;

export function GetBrowsers():Promise<Array<main.BrowserInfo>>;

export function GetInitialApp():Promise<string>;

export function GetInitialUser():Promise<string>;

export function GetLogoPath():Promise<string>;

export function GetMpvOptions():Promise<string>;

export function GetMpvPaths():Promise<Array<string>>;

export function GetProfileCount():Promise<number>;

export function GetProfilePhotos():Promise<Array<string>>;

export function GetProfiles():Promise<Array<main.Profile>>;

export function GetSelectedMpv():Promise<string>;

export function GetServerPort():Promise<number>;

export function GetServiceLibrary():Promise<Array<main.ServiceTemplate>>;

export function GetVersion():Promise<Record<string, string>>;

export function LaunchApp(arg1:main.AppConfig,arg2:string,arg3:string):Promise<void>;

export function Quit():Promise<void>;

export function SaveApps(arg1:string,arg2:Array<main.AppConfig>):Promise<void>;

export function SetMpvOptions(arg1:string):Promise<void>;

export function SetSelectedMpv(arg1:string):Promise<void>;

export function UpdateProfile(arg1:string,arg2:string,arg3:number,arg4:string,arg5:number):Promise<void>;
