// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseBrowser() {
  return window['go']['main']['App']['CloseBrowser']();
}

export function CreateProfile(arg1, arg2) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function GetApps(arg1) {
  return window['go']['main']['App']['GetApps'](arg1);
}

export function GetBrowsers() {
  return window['go']['main']['App']['GetBrowsers']();
}

export function GetLogoPath() {
  return window['go']['main']['App']['GetLogoPath']();
}

export function GetMpvOptions() {
  return window['go']['main']['App']['GetMpvOptions']();
}

export function GetMpvPaths() {
  return window['go']['main']['App']['GetMpvPaths']();
}

export function GetProfilePhotos() {
  return window['go']['main']['App']['GetProfilePhotos']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetSelectedMpv() {
  return window['go']['main']['App']['GetSelectedMpv']();
}

export function GetServerPort() {
  return window['go']['main']['App']['GetServerPort']();
}

export function GetServiceLibrary() {
  return window['go']['main']['App']['GetServiceLibrary']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LaunchApp(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchApp'](arg1, arg2, arg3);
}

export function LaunchBrowserAdmin(arg1) {
  return window['go']['main']['App']['LaunchBrowserAdmin'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveApps(arg1, arg2) {
  return window['go']['main']['App']['SaveApps'](arg1, arg2);
}

export function SetMpvOptions(arg1) {
  return window['go']['main']['App']['SetMpvOptions'](arg1);
}

export function SetSelectedMpv(arg1) {
  return window['go']['main']['App']['SetSelectedMpv'](arg1);
}

export function UpdateProfile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2, arg3, arg4, arg5);
}
